package com.example.working.pokergame;

import android.preference.PreferenceActivity;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;


public class PokerGame extends PreferenceActivity {
    final static int[] m_pokerImages = new int[]{
            R.drawable.poker1_1,
            R.drawable.poker1_2,
            R.drawable.poker1_3,
            R.drawable.poker1_4,
            R.drawable.poker2_1,
            R.drawable.poker2_2,
            R.drawable.poker2_3,
            R.drawable.poker2_4,
            R.drawable.poker3_1,
            R.drawable.poker3_2,
            R.drawable.poker3_3,
            R.drawable.poker3_4,
            R.drawable.poker4_1,
            R.drawable.poker4_2,
            R.drawable.poker4_3,
            R.drawable.poker4_4,
            R.drawable.poker5_1,
            R.drawable.poker5_2,
            R.drawable.poker5_3,
            R.drawable.poker5_4,
            R.drawable.poker6_1,
            R.drawable.poker6_2,
            R.drawable.poker6_3,
            R.drawable.poker6_4,
            R.drawable.poker7_1,
            R.drawable.poker7_2,
            R.drawable.poker7_3,
            R.drawable.poker7_4,
            R.drawable.poker8_1,
            R.drawable.poker8_2,
            R.drawable.poker8_3,
            R.drawable.poker8_4,
            R.drawable.poker9_1,
            R.drawable.poker9_2,
            R.drawable.poker9_3,
            R.drawable.poker9_4,
            R.drawable.poker10_1,
            R.drawable.poker10_2,
            R.drawable.poker10_3,
            R.drawable.poker10_4,
            R.drawable.poker11_1,
            R.drawable.poker11_2,
            R.drawable.poker11_3,
            R.drawable.poker11_4,
            R.drawable.poker12_1,
            R.drawable.poker12_2,
            R.drawable.poker12_3,
            R.drawable.poker12_4,
            R.drawable.poker13_1,
            R.drawable.poker13_2,
            R.drawable.poker13_3,
            R.drawable.poker13_4,
            R.drawable.poker14_1,
            R.drawable.poker15_1,
    };
    final static String[] m_pokerNames = new String[]{
        "ºÚÌÒA",
        "ºìÌÒA",
        "Ã·»¨A",
        "·½¿éA",
        "ºÚÌÒ2",
        "ºìÌÒ2",
        "Ã·»¨2",
        "·½¿é2",
        "ºÚÌÒ3",
        "ºìÌÒ3",
        "Ã·»¨3",
        "·½¿é3",
        "ºÚÌÒ4",
        "ºìÌÒ4",
        "Ã·»¨4",
        "·½¿é4",
        "ºÚÌÒ5",
        "ºìÌÒ5",
        "Ã·»¨5",
        "·½¿é5",
        "ºÚÌÒ6",
        "ºìÌÒ6",
        "Ã·»¨6",
        "·½¿é6",
        "ºÚÌÒ7",
        "ºìÌÒ7",
        "Ã·»¨7",
        "·½¿é7",
        "ºÚÌÒ8",
        "ºìÌÒ8",
        "Ã·»¨8",
        "·½¿é8",
        "ºÚÌÒ9",
        "ºìÌÒ9",
        "Ã·»¨9",
        "·½¿é9",
        "ºÚÌÒ10",
        "ºìÌÒ10",
        "Ã·»¨10",
        "·½¿é10",
        "ºÚÌÒJ",
        "ºìÌÒJ",
        "Ã·»¨J",
        "·½¿éJ",
        "ºÚÌÒQ",
        "ºìÌÒQ",
        "Ã·»¨Q",
        "·½¿éQ",
        "ºÚÌÒK",
        "ºìÌÒK",
        "Ã·»¨K",
        "·½¿éK",
        "Ğ¡Íõ",
        "´óÍõ",
    };
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addPreferencesFromResource(R.xml.mainlist);
    }

}
